package it.polimi.ingsw.controller;

/**
 * this enum contains the possible errors that the controller reports to the client
 */
public enum Error {

    /**
     *  IF THE LEADER CARD ARE WRONG, THE STARTING LEADER CARD ARE SENT AGAIN
     */
    STARTING_LEADER_CARD,

    /**
     * IF THE NUMBER OF RESOURCES IS WRONG, THE STARTING RESOURCES ARE SENT BACK
     */
    STARTING_RESOURCES,

    /**
     * IF THE MANAGE RESOURCES FAILS, THE INITIAL RESOURCES ARE SENT AGAIN
     */
    STARTING_MANAGE_RESOURCES,

    /**
     * IF THE ACTION IS INVALID OR IF THE DO ACTION FAILS, THE ACTION IS CANCELED AND THE POSSIBLE EXECUTABLE ACTIONS ARE SENT AGAIN
     */
    INVALID_ACTION,

    /**
     * IF THE MANAGE RESOURCES IS NOT VALID, THE MARKET ACTION RESOURCES ARE SENT BACK
     */
    MANAGE_RESOURCES
}
